import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'

import PageLayout from '@/components/layout'
import { ThemeProvider } from '@/components/layout/providers/theme-provider'

import './globals.css'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={rubik.className}>
        <ThemeProvider attribute='class' defaultTheme='dark'>
          <PageLayout>{children}</PageLayout>
        </ThemeProvider>
      </body>
    </html>
  )
}
